### ISSUE TITLE
The RobotEyes library would may to use different folders for baseline image.

### ISSUE THREAD

**Issue by MininAS** [jz-jess/RobotEyes#95]
Let our test asset contains several test suites. By some reason we need to use separeted baseline images folder for each suite.
We know the folder name should be set to IMAGES_DIR variable.

But when the report generator script start to create visualReport we get exception because IMAGES_DIR variable contains last set value from the last test suite and previous folder names can not be found.

`Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "........./python3.6/site-packages/RobotEyes/report_generator.py", line 74, in generate_report
    folder_name)
  File "........./python3.6/site-packages/RobotEyes/report_generator.py", line 227, in make_test_table
    for filename in os.listdir(baseline_folder + os.path.sep + folder_name):
FileNotFoundError: [Errno 2] No such file or directory: 'visual_images_original/Test_Case_Name_From_First_Suites'`

I image that it can be difficult to implement. It can need to creation of visualReport file during test running.

**Comment by jz-jess** [comment]
Im not actively working on this library as I'm busy working on other projects in my free time. If you can work on an implementation, I would be happy to take a look at it
